### ISSUE TITLE
Some operations block new connections

### ISSUE THREAD

**Issue by marrold** [gfoot/serialfs#4]
I've noticed after certain operations, SerialFS can't accept a new connection. 

I was using *SST which is a tool for loading ROM images onto a IFEL FLASH ROM module from the SerialFS. It worked fine, and I can continue to *CAT etc, but if I Ctrl + B the server doesn't notice the connection has dropped, or try to initialise a new one. Restarting the server fixes the issue.

Unfortunately this one's a bit beyond me to fix. Logs below:

```
Listening
Line open
Initializing link
Link active
Sending init code
Waiting...
unexpected: b'*'
unexpected: b'F'
unexpected: b'X'
unexpected: b'3'
unexpected: b','
unexpected: b'2'
unexpected: b'\n'
unexpected: b'\r'
Upgrading speed to 76800 baud
Ready
    CAT
    OSARGS &00 &00 0
    OSFIND &40
    OSARGS &02 &8c 1
    OSFIND &00
    OSFILE LOAD NFS360 ffff3500
    CAT
    OSARGS &00 &00 0
    OSFIND &40
    OSARGS &02 &8c 1
    OSFIND &00
    OSFILE LOAD DFS226 ffff3500
```

**Comment by gfoot** [comment]
Can you give an example of usage of SST that I can try please? I'm not familiar with the tool.

**Comment by marrold** [comment]
*SST is for a Flash based ROM board so probably hard to replicate, however I've just managed to replicate it with a simple *LOAD

I used this ssd - https://bbcmicro.co.uk/game.php?id=25
```
*DIN chuckie.ssd
*LOAD chuckie
```

And then after a Ctrl + B, or indeed powering off the machine, SerialFS doesn't try to re-initialise the connection until its restarted.

**Comment by gfoot** [comment]
Great and by Ctrl B you mean Ctrl Break?

**Comment by marrold** [comment]
Yes, Ctrl Break sorry. I thought perhaps it wasn't setting DSR low to re-trigger the server initialisation but the behaviour is the same when powering off the machine or removing the serial cable.

**Comment by gfoot** [comment]
I'm afraid I can't reproduce this, I wonder if it's related to the DSR/CTS difference with your cable?  My serial adaptor seems to toggle DSR when the Beeb leaves listening mode, presumably based on the Beeb's RTS line, and the server checks for this in a few places.  There may be some places where it doesn't do the check but should; however in general this works, and specifically in the *LOAD CHUCKIE case it is working for me.

**Comment by marrold** [comment]
This was indeed related to the syntax error introduced in https://github.com/gfoot/serialfs/pull/2, apologies !
